### ISSUE TITLE
Spotify playlists dont work

### ISSUE THREAD

**Issue by uShifty** [MeridianGH/suitbot#2]
When debugging I noticed it entered playSong funciton instead of playPlaylist. 
when I changed `if (query.match(/^https?:\/\/(?:open|play)\.spotify\.com\/user\/([\w\d]+)\/playlist\/[\w\d]+$/i) ||
query.match(/^(?!.*\?.*\bv=)https:\/\/www\.youtube\.com\/.*\?.*\blist=.*$/i)) {` 
to this 
`if (query.match(/^https?:\/\/(?:open|play)\.spotify\.com\/playlist\/[\w\d]+$/i) || query.match(/^(?!.*\?.*\bv=)https:\/\/www\.youtube\.com\/.*\?.*\blist=.*$/i)) {` 
it will enter the correct function and it will find the songs on youtube but no music ends up playing. I say it finds the song because I added a log in 
`playlist.songs.forEach(song => {
    console.log(song)
    song.requestedBy = interaction.member.displayName
})` 
But if I wanted to play a singular song from spotify it will work

**Comment by MeridianGH** [comment]
Thank you for your issue!
The regex for Spotify playlist was indeed incorrect, with your corrected regex I was able to get Spotify playlists working as well. The bot didn't end up playing anything because it crashed when trying to send the embed with an empty author string, as Spotify playlists have a dictionary object as their author and their author needs to be accessed explicitly.
